### ISSUE TITLE
execution order (and windows?)

### ISSUE THREAD

**Issue by jshwlkr** [gregwolanski/eleventy-tailwindcss-alpinejs-starter#10]
I think on Windows, and potentially other environments, `eleventy --serve` never actually returns so `npx tailwindcss` never executes.

**Comment by gregwolanski** [comment]
Hi Joshua! Thank you for your comment. Did you test it? : )

**Comment by jshwlkr** [comment]
Yep.

**Comment by gregwolanski** [comment]
Thank you, Joshua. I wasn’t able to reproduce this problem on localhost, but Netlify stopped working with `&` instead of `&&`. Fixed: https://github.com/gregwolanski/eleventy-tailwindcss-alpinejs-starter/commit/78e6aface387b30e9a08f2ca50689a772d889704
